# Generated by Django 6.0 on 2026-04-18 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_activity_detail',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
                ('Finish_Date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Actividad',
                'verbose_name_plural': 'Detalles de Actividades',
                'db_table': 'tbl_activity_detail',
            },
        ),
        migrations.CreateModel(
            name='Tbl_Category',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'tbl_category',
            },
        ),
        migrations.CreateModel(
            name='Tbl_users',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=5000)),
                ('Update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'tbl_users',
            },
        ),
        migrations.CreateModel(
            name='tbl_activities',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
                ('Finish_Date', models.DateTimeField(blank=True, null=True)),
                ('Id_activity_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='gamificacion.tbl_activity_detail')),
                ('Id_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='gamificacion.tbl_category')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'tbl_activities',
            },
        ),
        migrations.CreateModel(
            name='Tbl_Penalized',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Level', models.CharField(max_length=5000)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('Id_Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalizaciones', to='gamificacion.tbl_users')),
            ],
            options={
                'verbose_name': 'Penalizado',
                'verbose_name_plural': 'Penalizados',
                'db_table': 'tbl_penalized',
            },
        ),
        migrations.AddField(
            model_name='tbl_category',
            name='Id_Users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='gamificacion.tbl_users'),
        ),
        migrations.CreateModel(
            name='Tbl_accomplishments_history',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('Id_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='gamificacion.tbl_activities')),
                ('Id_Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='gamificacion.tbl_users')),
            ],
            options={
                'verbose_name': 'Historial de Logros',
                'verbose_name_plural': 'Historial de Logros',
                'db_table': 'tbl_accomplishments_history',
            },
        ),
        migrations.CreateModel(
            name='tbl_VIP',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Id_Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vips', to='gamificacion.tbl_users')),
            ],
            options={
                'verbose_name': 'VIP',
                'verbose_name_plural': 'VIPs',
                'db_table': 'tbl_vip',
            },
        ),
    ]
