# Generated by Django 5.2.13 on 2026-04-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_users',
            name='level',
            field=models.CharField(blank=True, default='1', max_length=5000),
        ),
        migrations.AlterField(
            model_name='tbl_users',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
