# Generated by Django 5.2.13 on 2026-04-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacion', '0002_alter_tbl_users_level_alter_tbl_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_activities',
            name='xp',
            field=models.IntegerField(default=10),
        ),
    ]
