# Generated by Django 5.2.13 on 2026-04-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacion', '0003_tbl_activities_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_accomplishments_history',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbl_users',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
