# Generated by Django 5.2.13 on 2026-04-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacion', '0004_tbl_accomplishments_history_completed_tbl_users_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_category',
            name='Id_Users',
        ),
        migrations.AddField(
            model_name='tbl_users',
            name='categoria_activa',
            field=models.IntegerField(default=1),
        ),
    ]
